### ISSUE TITLE
Fix for broken terminal

### ISSUE THREAD

**Issue by Ondralol** [Linux-Tech-Tips/terminal_snake#1]
Use alt screen for the game window

escape sequence for entering new alt screen "\033[?1049h\033[H"
escape sequence for closing alt screen "\033[?1049l"

**Comment by Linux-Tech-Tips** [comment]
Next time, please include a further description of the issue.

Currently, the escape codes used for screen saving/restoring are `ESC[?47h` and `ESC[?47l`.

I take it the suggested escape sequences (`ESC[?1049h` - without the trailing cursor home sequence - and `ESC[?1049l`) work better? Will investigate, thanks
